
/** ALARM **/
export const TIME_CHANGED = 'TIME_CHANGED';
export const TIME_NEW = 'TIME_NEW';
export const TIME_DELETE = 'TIME_DELETE';
export const SNOOZE_PRESSED = 'SNOOZE_PRESSED';
export const SNOOZE_DELETE = 'SNOOZE_DELETE';
export const ENABLED_PRESSED = 'ENABLED_PRESSED';
export const REPEAT_PRESSED = 'REPEAT_PRESSED';
export const REPEAT_BUTTON_PRESSED = 'REPEAT_BUTTON_PRESSED';
export const ALARM_STATE_LOADED = 'ALARM_STATE_LOADED';
/** ALARM **/

/** NAVIGATION **/
export const TAB_PRESSED = 'TAB_PRESSED';
export const VIDEO_PLAYER_LOAD_END = 'VIDEO_PLAYER_LOAD_END';
export const VIDEO_PLAYER_ERROR = 'VIDEO_PLAYER_ERROR';
export const APP_LAUNCHED = 'APP_LAUNCHED';
export const ORIENTATION_CHANGED = 'ORIENTATION_CHANGED';
export const RINGTONE_MODAL_DISMISSED = 'RINGTONE_MODAL_DISMISSED';
export const STATE_LOAD_ERROR = 'STATE_LOAD_ERROR';
/** NAVIGATION **/



